// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "io.github.jerryshell.mattermost-plugin-post-email",
  "name": "Post Email",
  "description": "Send Post To Email",
  "version": "0.1.0",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "SMTP_SERVER",
        "display_name": "SMTP Server",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": "smtp.gmail.com"
      },
      {
        "key": "SMTP_SERVER_PORT",
        "display_name": "SMTP Server Port",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": "587"
      },
      {
        "key": "SMTP_SERVER_USERNAME",
        "display_name": "SMTP Server Username",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": ""
      },
      {
        "key": "SMTP_SERVER_PASSWORD",
        "display_name": "SMTP Server Password",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": ""
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
